export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_FONTS_LOADED = 'SET_FONTS_LOADED';
export const SET_VALIDATION_ERRORS = 'SET_VALIDATION_ERRORS';
export const EDIT_PROFILE = 'EDIT_PROFILE';
