import {
  ANDROID_GOOGLE_CLIENT_ID,
  API_BASE_URL,
  FACEBOOK_APP_ID,
  IMAGE_BASE_URL,
  IOS_GOOGLE_CLIENT_ID,
  CLIENT_ID,
} from 'react-native-dotenv';

const config = {
  API_BASE_URL,
  IMAGE_BASE_URL,
  FACEBOOK_APP_ID,
  ANDROID_GOOGLE_CLIENT_ID,
  IOS_GOOGLE_CLIENT_ID,
  CLIENT_ID,
};

export default config;
