# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

PROJECT_NAME = ENV["PROJECT_NAME"]
XCODE_PROJECT = "#{PROJECT_NAME}.xcodeproj"
XCODE_WORKSPACE = "#{PROJECT_NAME}.xcworkspace"
OUTPUT_DIRECTORY = "./fastlane/builds"
IPA_DIRECTORY = "#{OUTPUT_DIRECTORY}/#{PROJECT_NAME}.ipa"

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"
ENV["FASTLANE_ITC_TEAM_ID"] = ENV["APP_STORE_TEAM_ID"]

platform :ios do
  private_lane :build do
    configuration_name = "Release"
    export_options_method = "appstore"
    code_sign_identity = "iPhone Distribution"
    MY_APP_ID = ENV["APP_IDENTIFIER"]
    MY_PROFILE = ENV["APP_PROVISIONING_PROFILE_NAME"]
    MY_TEAM = ENV["DEVELOPER_TEAM_ID"]

    increment_build_number(xcodeproj: XCODE_PROJECT)

    settings_to_override = {
      :BUNDLE_IDENTIFIER => MY_APP_ID,
      :PROVISIONING_PROFILE_SPECIFIER => MY_PROFILE,
      :DEVELOPMENT_TEAM => MY_TEAM,
    }

    create_keychain(
      name: ENV["CI_KEYCHAIN_NAME"],
      password: ENV["CI_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      app_identifier: ENV["APP_IDENTIFIER"],
      git_url: ENV["GIT_REPO_URL"],
      type: "appstore",
      username: ENV["APPLE_ID"],
      team_id: ENV["DEVELOPER_TEAM_ID"],
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: XCODE_PROJECT,
      team_id: ENV["DEVELOPER_TEAM_ID"],
      code_sign_identity: code_sign_identity,
      bundle_identifier: MY_APP_ID,
      profile_name: MY_PROFILE
    )

    gym(
      scheme: PROJECT_NAME,
      workspace: XCODE_WORKSPACE,
      silent: true,
      configuration: configuration_name,
      xcargs: `#{settings_to_override} -UseNewBuildSystem=YES`,
      output_directory: OUTPUT_DIRECTORY,
      output_name: "#{PROJECT_NAME}.ipa",
      export_options: {
        method: "appstore",
        signingStyle: "manual",
        provisioningProfiles: {
            MY_APP_ID => MY_PROFILE
        }
      }
    )

    upload_to_testflight(
      username: ENV["APPLE_ID"],
      app_identifier: ENV["APP_IDENTIFIER"],
      apple_id: ENV["APPLICATION_ID"],
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  desc "Create Signed Build"
  lane :beta do
    build
  end
end